### ISSUE TITLE
Consider removing Q1RMN8 due to `@`

### ISSUE THREAD

**Issue by csdaw** [HaoGroup-ProtContLib/Protein-Contaminant-Libraries-for-DDA-and-DIA-Proteomics#2]
Hi there,

First thanks for this resource!

I'd like to suggest removing the protein Q1RMN8 from your contaminants FASTA (or modifying its header) as the gene name for this protein has an `@` symbol in it for some reason. I've found this causes MSFragger to fail with an error during its main search (and may cause other software to fail as well).

**Comment by HaoGroup** [comment]
Hello, 

Thank you for bringing this to our attention. We've gone ahead and updated both the universal and cell culture databases to remove the "@" symbol.
